
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 1, 1, 12, '2023-09-22', 3.00, 30, 'Salapärane roog', 'Sisaldab ainult välismaiseid komponente', 9, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 1, 1, 13, '2023-09-22', 2.00, 6, 'Moonirullid', 'Moonid, nisujahu, gluteen', 8, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 1, 1, 15, '2023-09-23', 3.00, 11, 'Pestopasta', 'Minu itaalia vanaisa iidse retsepti järgi tehtud pasta, mida sa pead kindlasti maitsma! Koostisosad: muru, õunapuulehed, basiiliku lõhna- ja maitseaine, veel natuke muru', 5, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 2, 2, 9, '2023-09-25', 4.00, 10, 'Ühepajatoit', 'Sisaldab kõike, mis kapis üle jäänud...', 9, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 2, 2, 10, '2023-09-24', 2.00, 10, 'Mannapuder', 'Manna, vesi, sool, head mõtted', 2, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 3, 3, 11, '2023-09-26', 5.00, 10, 'Makaronid hakklihaga', 'Makaronid, hakkliha', 5, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 3, 3, 11, '2023-10-05', 3.00, 10, 'Tomatisupp', 'Klassikaline tomatisupp', 1, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 4, 4, 14, '2023-09-30', 5.00, 9, 'Soolasupp', 'Sool, vesi, armastus', 1, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 4, 4, 8, '2023-09-23', 2.00, 8, 'Eilsed saiakesed', 'Tegelikult üleeilsed, aga ära seda kellelegi ütle', 8, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 5, 5, 12, '2023-09-25', 8.00, 4, 'Kaerahelbepuder', 'Kaer jm hobuste söök', 2, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 5, 5, 15, '2023-09-24', 7.00, 6, 'Caesari salat', 'Julius Caesar mõrvati 14. märtsil 44eKr, aga sellest salatist ei teadnud ta midagi. Küll aga maitseb see suurepäraselt ja sa peaksid tulema seda sööma! Oma tool kaasa...', 6, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 6, 6, 19, '2023-09-22', 7.00, 4, 'Tiramisu', 'Tiramisut pakun noh', 7, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 7, 7, 12, '2023-10-01', 1.00, 2, 'Riisipuder', 'Riis, vesi. Hästi mage.', 2, 'A');
INSERT INTO eat.offer (id, user_id, location_id, time, date, price, total_portions, name, description, food_group_id, status) VALUES (default, 7, 7, 11, '2023-10-02', 9.00, 2, 'Kurgisushi', 'kurk, sool, majonees, ketšup, sinep, seesamiseemned, männikäbid', 4, 'A');

