INSERT INTO eat.food_group (id, name) VALUES (DEFAULT, 'supp');
INSERT INTO eat.food_group (id, name) VALUES (DEFAULT, 'puder');
INSERT INTO eat.food_group (id, name) VALUES (DEFAULT, 'praad');
INSERT INTO eat.food_group (id, name) VALUES (DEFAULT, 'sushi');
INSERT INTO eat.food_group (id, name) VALUES (DEFAULT, 'pasta');
INSERT INTO eat.food_group (id, name) VALUES (DEFAULT, 'salat');
INSERT INTO eat.food_group (id, name) VALUES (DEFAULT, 'magustoit');
INSERT INTO eat.food_group (id, name) VALUES (DEFAULT, 'pagaritooted');
INSERT INTO eat.food_group (id, name) VALUES (DEFAULT, 'varia');